import { Product } from '../types';

// ============================================
// BRASS TERMINALS
// ============================================
export const brassTerminalProducts: Product[] = [
  // Ring Series Terminals
  {
    id: "bt-ring-la103",
    name: "Ring Series Terminal - LA103",
    slug: "ring-terminal-la103",
    category: "Brass Terminal",
    subcategory: "Ring Series",
    description: "Ring terminal with 7.00mm OD for 1.50-2.20 sq mm cable. Available in small hole (3.20mm ID) and big hole (4.20mm ID) variants. Material: CuZn-63/37.",
    partNumber: "SWT001003",
    featured: true,
    variantType: "spec",
    defaultVariant: "la103-small",
    variants: [
      {
        id: "la103-small",
        code: "SWT001003S",
        images: ["/products/brass-terminals/ring-series/SWT001003S.jpg"],
        name: "Small Hole (3.20mm ID)",
        specifications: {
          "OD": "7.00mm",
          "ID": "3.20mm",
          "Cable Size": "1.50-2.20 sq mm",
          "Material": "CuZn-63/37",
          "Packing": "Spool-8000 / Cut-1000",
        },
      },
      {
        id: "la103-medium",
        code: "SWT001003M",
        images: ["/products/brass-terminals/ring-series/SWT001003M.jpg"],
        name: "Medium Hole (3.70mm ID)",
        specifications: {
          "OD": "7.00mm",
          "ID": "3.70mm",
          "Cable Size": "1.50-2.20 sq mm",
          "Material": "CuZn-63/37",
          "Packing": "Spool-8000 / Cut-1000",
        },
      },
      {
        id: "la103-big",
        code: "SWT001003B",
        images: ["/products/brass-terminals/ring-series/SWT001003B.jpg"],
        name: "Big Hole (4.20mm ID)",
        specifications: {
          "OD": "7.00mm",
          "ID": "4.20mm",
          "Cable Size": "1.50-2.20 sq mm",
          "Material": "CuZn-63/37",
          "Packing": "Spool-8000 / Cut-1000",
        },
      },
    ],
    specifications: {
      "OD": "7.00mm",
      "Cable Size": "1.50-2.20 sq mm",
      "Material": "CuZn-63/37",
    },
    tags: ["terminal", "ring", "brass", "la103"],
    applications: ["Automotive", "Electrical Connections"],
  },
  {
    id: "bt-ring-complete",
    name: "Ring Series Terminals - Complete Range",
    slug: "ring-series-terminals-complete",
    category: "Brass Terminal",
    subcategory: "Ring Series",
    description: "Complete range of ring series terminals with various OD/ID combinations. Available in brass (CuZn-63/37) with tin plating options. Ideal for secure electrical connections in automotive applications.",
    featured: true,
    specifications: {
      "Material": "CuZn-63/37 Brass",
      "Plating Options": "Plain, Tin Plated",
      "Applications": "Automotive, Industrial",
    },
    tags: ["terminal", "ring", "brass", "complete-range"],
    applications: ["Automotive", "Industrial", "Electrical Connections"],
  },
  // Fork/Jointer Series
  {
    id: "bt-fork-1",
    name: "Fork Series Terminals",
    slug: "fork-series-terminals",
    category: "Brass Terminal",
    subcategory: "Fork Series",
    description: "Fork/spade terminals for easy connect-disconnect applications. Multiple sizes available for various cable gauges.",
    featured: true,
    specifications: {
      "Material": "CuZn-63/37 Brass",
      "Type": "Fork/Spade",
      "Applications": "Quick connect/disconnect",
    },
    tags: ["terminal", "fork", "spade", "brass"],
    applications: ["Automotive", "Electrical Connections"],
  },
  {
    id: "bt-jointer-1",
    name: "Jointer Series Terminals",
    slug: "jointer-series-terminals",
    category: "Brass Terminal",
    subcategory: "Jointer Series",
    description: "Jointer terminals for wire-to-wire connections. Precision-engineered for reliable electrical joints.",
    specifications: {
      "Material": "Brass",
      "Type": "Jointer/Butt",
      "Applications": "Wire splicing",
    },
    tags: ["terminal", "jointer", "brass"],
    applications: ["Automotive", "Wire Connections"],
  },
  // Bullet Series
  {
    id: "bt-bullet-1",
    name: "Bullet Series Terminals - Male",
    slug: "bullet-terminals-male",
    category: "Brass Terminal",
    subcategory: "Bullet Series",
    description: "Male bullet terminals for automotive wiring. Available in multiple sizes for various applications.",
    featured: true,
    specifications: {
      "Type": "Male Bullet",
      "Material": "Brass",
      "Applications": "Automotive wiring connectors",
    },
    tags: ["terminal", "bullet", "male", "brass"],
    applications: ["Automotive", "Electrical Connections"],
  },
  {
    id: "bt-bullet-2",
    name: "Bullet Series Terminals - Female",
    slug: "bullet-terminals-female",
    category: "Brass Terminal",
    subcategory: "Bullet Series",
    description: "Female bullet terminals designed to mate with male bullet connectors. Ensures secure electrical connections.",
    specifications: {
      "Type": "Female Bullet",
      "Material": "Brass",
      "Applications": "Automotive wiring connectors",
    },
    tags: ["terminal", "bullet", "female", "brass"],
    applications: ["Automotive", "Electrical Connections"],
  },
  // Fuse Series
  {
    id: "bt-fuse-1",
    name: "Fuse Series Terminals",
    slug: "fuse-series-terminals",
    category: "Brass Terminal",
    subcategory: "Fuse Series",
    description: "Terminals designed specifically for fuse connections. High conductivity brass construction.",
    specifications: {
      "Material": "High Conductivity Brass",
      "Applications": "Fuse holders, Fuse boxes",
    },
    tags: ["terminal", "fuse", "brass"],
    applications: ["Automotive", "Fuse Connections"],
  },
  // 090 Series
  {
    id: "bt-090-1",
    name: "090 Series Terminals",
    slug: "090-series-terminals",
    category: "Brass Terminal",
    subcategory: "090 Series",
    description: "090 Series terminals (2.3mm) for automotive connectors. Male and female variants available.",
    featured: true,
    specifications: {
      "Series": "090 (2.3mm)",
      "Variants": "Male, Female",
      "Applications": "Automotive connectors",
    },
    tags: ["terminal", "090", "brass"],
    applications: ["Automotive", "Connectors"],
  },
  // 0110 Series
  {
    id: "bt-0110-1",
    name: "0110 Series Terminals",
    slug: "0110-series-terminals",
    category: "Brass Terminal",
    subcategory: "0110 Series",
    description: "0110 Series terminals (2.8mm) for automotive applications. Precision-manufactured for reliable connections.",
    specifications: {
      "Series": "0110 (2.8mm)",
      "Variants": "Male, Female",
      "Applications": "Automotive connectors",
    },
    tags: ["terminal", "0110", "brass"],
    applications: ["Automotive", "Connectors"],
  },
  // 0187 Series
  {
    id: "bt-0187-1",
    name: "0187 Series Terminals",
    slug: "0187-series-terminals",
    category: "Brass Terminal",
    subcategory: "0187 Series",
    description: "0187 Series terminals (4.8mm) blade terminals for medium duty applications.",
    specifications: {
      "Series": "0187 (4.8mm)",
      "Type": "Blade Terminal",
      "Applications": "Medium duty connections",
    },
    tags: ["terminal", "0187", "brass"],
    applications: ["Automotive", "Medium Duty"],
  },
  // 0250 Series
  {
    id: "bt-0250-1",
    name: "0250 Series Terminals",
    slug: "0250-series-terminals",
    category: "Brass Terminal",
    subcategory: "0250 Series",
    description: "0250 Series terminals (6.3mm) for standard automotive connections. High current capacity.",
    featured: true,
    specifications: {
      "Series": "0250 (6.3mm)",
      "Type": "Blade Terminal",
      "Applications": "High current automotive",
    },
    tags: ["terminal", "0250", "brass"],
    applications: ["Automotive", "High Current"],
  },
  // 0312 Series
  {
    id: "bt-0312-1",
    name: "0312 Series Terminals",
    slug: "0312-series-terminals",
    category: "Brass Terminal",
    subcategory: "0312 Series",
    description: "0312 Series terminals (7.8mm) for heavy-duty automotive applications.",
    specifications: {
      "Series": "0312 (7.8mm)",
      "Type": "Blade Terminal",
      "Applications": "Heavy duty connections",
    },
    tags: ["terminal", "0312", "brass"],
    applications: ["Automotive", "Heavy Duty"],
  },
  // 0375 Series
  {
    id: "bt-0375-1",
    name: "0375 Series Terminals",
    slug: "0375-series-terminals",
    category: "Brass Terminal",
    subcategory: "0375 Series",
    description: "0375 Series terminals (9.5mm) for extra heavy-duty applications.",
    specifications: {
      "Series": "0375 (9.5mm)",
      "Type": "Blade Terminal",
      "Applications": "Extra heavy duty",
    },
    tags: ["terminal", "0375", "brass"],
    applications: ["Automotive", "Extra Heavy Duty"],
  },
  // Special Series
  {
    id: "bt-special-1",
    name: "Special Series Terminals",
    slug: "special-series-terminals",
    category: "Brass Terminal",
    subcategory: "Special Series",
    description: "Specialized terminals for unique applications. Custom designs available.",
    specifications: {
      "Type": "Special/Custom",
      "Applications": "Custom requirements",
    },
    tags: ["terminal", "special", "custom", "brass"],
    applications: ["Custom Applications"],
  },
  // Brass Lugs
  {
    id: "bt-lugs-1",
    name: "Brass Cable Lugs",
    slug: "brass-cable-lugs",
    category: "Brass Terminal",
    subcategory: "Brass Lugs",
    description: "Heavy-duty brass cable lugs for battery and ground connections. Available in various hole sizes and cable capacities.",
    featured: true,
    specifications: {
      "Material": "High-grade Brass",
      "Applications": "Battery terminals, Ground connections",
      "Variants": "Multiple sizes",
    },
    tags: ["lugs", "brass", "battery", "cable"],
    applications: ["Automotive", "Battery Connections"],
  },
  // Brass Sheet Terminal
  {
    id: "bt-sheet-1",
    name: "Brass Sheet Terminals",
    slug: "brass-sheet-terminals",
    category: "Brass Terminal",
    subcategory: "Sheet Terminals",
    description: "Flat brass sheet terminals. Also available in copper sheet for bulk quantity orders.",
    specifications: {
      "Material": "Brass / Copper (bulk)",
      "Type": "Sheet Terminal",
    },
    tags: ["terminal", "sheet", "brass"],
    applications: ["Automotive", "Electrical"],
  },
  // Brass Battery Terminal
  {
    id: "bt-battery-1",
    name: "Brass Battery Terminals",
    slug: "brass-battery-terminals",
    category: "Brass Terminal",
    subcategory: "Battery Terminals",
    description: "Premium brass battery terminals for automotive batteries. Excellent conductivity and corrosion resistance.",
    featured: true,
    specifications: {
      "Material": "Premium Brass",
      "Applications": "Automotive batteries",
      "Features": "Corrosion resistant",
    },
    tags: ["terminal", "battery", "brass"],
    applications: ["Automotive", "Battery"],
  },
  {
    id: "bt-battery-2",
    name: "Lead Battery Terminals",
    slug: "lead-battery-terminals",
    category: "Brass Terminal",
    subcategory: "Battery Terminals",
    description: "Lead alloy battery terminals for heavy-duty applications.",
    specifications: {
      "Material": "Lead Alloy",
      "Applications": "Heavy duty batteries",
    },
    tags: ["terminal", "battery", "lead"],
    applications: ["Automotive", "Heavy Duty Battery"],
  },
];
