import { Product } from '../types';

// ============================================
// CABLE MANAGEMENT & PROTECTION
// ============================================

// RUBBER GROMMETS
export const rubberGrommetProducts: Product[] = [
  {
    id: "grommet-001",
    name: "Rubber Grommet - 25.60mm x 19.30mm",
    slug: "rubber-grommet-25.60x19.30",
    category: "Cable Management",
    subcategory: "Rubber Grommet",
    description: "Rubber grommet for wire passage and protection. Size: 25.60mm x 19.30mm.",
    partNumber: "SI0100001",
    image: "/products/cable-management/rubber-grommet/SI0100001.jpg",
    specifications: {
      "Outer Dimension": "25.60mm",
      "Inner Dimension": "19.30mm",
      "Material": "Rubber",
      "Packing": "100 Pcs",
    },
    tags: ["grommet", "rubber", "wire-protection"],
    applications: ["Automotive", "Wire Passage", "Panel Mounting"],
  },
  {
    id: "grommet-002",
    name: "Rubber Grommet - 12.60mm x 12.90mm",
    slug: "rubber-grommet-12.60x12.90",
    category: "Cable Management",
    subcategory: "Rubber Grommet",
    description: "Rubber grommet for wire passage. Size: 12.60mm x 12.90mm.",
    partNumber: "SI0100002",
    image: "/products/cable-management/rubber-grommet/SI0100002.jpg",
    specifications: {
      "Outer Dimension": "12.60mm",
      "Inner Dimension": "12.90mm",
      "Material": "Rubber",
      "Packing": "100 Pcs",
    },
    tags: ["grommet", "rubber", "wire-protection"],
    applications: ["Automotive", "Wire Passage"],
  },
  {
    id: "grommet-003",
    name: "Rubber Grommet - 21.20mm x 12.60mm",
    slug: "rubber-grommet-21.20x12.60",
    category: "Cable Management",
    subcategory: "Rubber Grommet",
    description: "Rubber grommet for wire passage. Size: 21.20mm x 12.60mm.",
    partNumber: "SI0100003",
    image: "/products/cable-management/rubber-grommet/SI0100003.jpg",
    specifications: {
      "Outer Dimension": "21.20mm",
      "Inner Dimension": "12.60mm",
      "Material": "Rubber",
      "Packing": "100 Pcs",
    },
    tags: ["grommet", "rubber", "wire-protection"],
    applications: ["Automotive", "Wire Passage"],
  },
  {
    id: "grommet-004",
    name: "Rubber Grommet - Large",
    slug: "rubber-grommet-large",
    category: "Cable Management",
    subcategory: "Rubber Grommet",
    description: "Large rubber grommet for bulk wire passage.",
    partNumber: "SI0100004",
    image: "/products/cable-management/rubber-grommet/SI0100004.jpg",
    featured: true,
    specifications: {
      "Size": "Large",
      "Material": "Rubber",
      "Packing": "100 Pcs",
    },
    tags: ["grommet", "rubber", "large", "wire-protection"],
    applications: ["Automotive", "Heavy Duty Wire Passage"],
  },
  {
    id: "grommet-011",
    name: "Rubber Grommet - 70mm x 23mm",
    slug: "rubber-grommet-70x23",
    category: "Cable Management",
    subcategory: "Rubber Grommet",
    description: "Large rubber grommet. Size: 70mm x 23mm.",
    partNumber: "SI0100011",
    image: "/products/cable-management/rubber-grommet/SI0100011.jpg",
    specifications: {
      "Outer Dimension": "70mm",
      "Inner Dimension": "23mm",
      "Material": "Rubber",
      "Packing": "100 Pcs",
    },
    tags: ["grommet", "rubber", "large"],
    applications: ["Automotive", "Large Wire Bundle"],
  },
  {
    id: "grommet-012",
    name: "Rubber Grommet - 42mm x 37mm",
    slug: "rubber-grommet-42x37",
    category: "Cable Management",
    subcategory: "Rubber Grommet",
    description: "Rubber grommet. Size: 42mm x 37mm.",
    partNumber: "SI0100012",
    image: "/products/cable-management/rubber-grommet/SI0100012.jpg",
    specifications: {
      "Outer Dimension": "42mm",
      "Inner Dimension": "37mm",
      "Material": "Rubber",
      "Packing": "100 Pcs",
    },
    tags: ["grommet", "rubber"],
    applications: ["Automotive", "Wire Passage"],
  },
  {
    id: "grommet-013",
    name: "Rubber Grommet - 54mm x 59mm",
    slug: "rubber-grommet-54x59",
    category: "Cable Management",
    subcategory: "Rubber Grommet",
    description: "Large rubber grommet. Size: 54mm x 59mm.",
    partNumber: "SI0100013",
    image: "/products/cable-management/rubber-grommet/SI0100013.jpg",
    specifications: {
      "Outer Dimension": "54mm",
      "Inner Dimension": "59mm",
      "Material": "Rubber",
      "Packing": "100 Pcs",
    },
    tags: ["grommet", "rubber", "large"],
    applications: ["Automotive", "Large Wire Bundle"],
  },
  {
    id: "grommet-014",
    name: "Rubber Grommet - 70mm x 37mm",
    slug: "rubber-grommet-70x37",
    category: "Cable Management",
    subcategory: "Rubber Grommet",
    description: "Large rubber grommet. Size: 70mm x 37mm.",
    partNumber: "SI0100014",
    image: "/products/cable-management/rubber-grommet/SI0100014.jpg",
    specifications: {
      "Outer Dimension": "70mm",
      "Inner Dimension": "37mm",
      "Material": "Rubber",
      "Packing": "100 Pcs",
    },
    tags: ["grommet", "rubber", "large"],
    applications: ["Automotive", "Heavy Duty"],
  },
  {
    id: "grommet-015",
    name: "Rubber Grommet - 42mm",
    slug: "rubber-grommet-42",
    category: "Cable Management",
    subcategory: "Rubber Grommet",
    description: "Rubber grommet. Size: 42mm.",
    partNumber: "SI0100015",
    image: "/products/cable-management/rubber-grommet/SI0100015.jpg",
    specifications: {
      "Dimension": "42mm",
      "Material": "Rubber",
      "Packing": "100 Pcs",
    },
    tags: ["grommet", "rubber"],
    applications: ["Automotive", "Wire Passage"],
  },
  {
    id: "grommet-016",
    name: "Rubber Grommet - 37mm",
    slug: "rubber-grommet-37",
    category: "Cable Management",
    subcategory: "Rubber Grommet",
    description: "Rubber grommet. Size: 37mm.",
    partNumber: "SI0100016",
    image: "/products/cable-management/rubber-grommet/SI0100016.jpg",
    specifications: {
      "Dimension": "37mm",
      "Material": "Rubber",
      "Packing": "100 Pcs",
    },
    tags: ["grommet", "rubber"],
    applications: ["Automotive", "Wire Passage"],
  },
  {
    id: "grommet-017",
    name: "Rubber Grommet - 50mm x 38mm",
    slug: "rubber-grommet-50x38",
    category: "Cable Management",
    subcategory: "Rubber Grommet",
    description: "Rubber grommet. Size: 50mm x 38mm.",
    partNumber: "SI0100017",
    specifications: {
      "Outer Dimension": "50mm",
      "Inner Dimension": "38mm",
      "Material": "Rubber",
      "Packing": "100 Pcs",
    },
    tags: ["grommet", "rubber"],
    applications: ["Automotive", "Wire Passage"],
  },
];

// WIRE SEALS & DUMMY SEALS
export const wireSealProducts: Product[] = [
  {
    id: "seal-wire-001",
    name: "Wire Seal - Type 1",
    slug: "wire-seal-type-1",
    category: "Cable Management",
    subcategory: "Wire Seal",
    description: "Wire seal for waterproof wire passage in connectors. Type 1.",
    partNumber: "SI0002001",
    image: "/products/cable-management/seal/SI0002001.jpg",
    featured: true,
    specifications: {
      "Type": "Wire Seal",
      "Application": "Waterproof Connectors",
      "Packing": "100 Pcs",
    },
    tags: ["seal", "wire", "waterproof"],
    applications: ["Automotive", "Waterproof Connectors"],
  },
  {
    id: "seal-wire-002",
    name: "Wire Seal - Type 2",
    slug: "wire-seal-type-2",
    category: "Cable Management",
    subcategory: "Wire Seal",
    description: "Wire seal for waterproof wire passage. Type 2.",
    partNumber: "SI0002002",
    image: "/products/cable-management/seal/SI0002002.jpg",
    specifications: {
      "Type": "Wire Seal",
      "Application": "Waterproof Connectors",
      "Packing": "100 Pcs",
    },
    tags: ["seal", "wire", "waterproof"],
    applications: ["Automotive", "Waterproof Connectors"],
  },
  {
    id: "seal-dummy-003",
    name: "Dummy Seal - Type 3",
    slug: "dummy-seal-type-3",
    category: "Cable Management",
    subcategory: "Dummy Seal",
    description: "Dummy seal for unused connector cavities. Prevents water and dust ingress.",
    partNumber: "SI0002003",
    image: "/products/cable-management/seal/SI0002003.jpg",
    specifications: {
      "Type": "Dummy Seal",
      "Application": "Unused Cavities",
      "Packing": "100 Pcs",
    },
    tags: ["seal", "dummy", "waterproof"],
    applications: ["Automotive", "Connector Protection"],
  },
  {
    id: "seal-wire-004",
    name: "Wire Seal - Type 4",
    slug: "wire-seal-type-4",
    category: "Cable Management",
    subcategory: "Wire Seal",
    description: "Wire seal for waterproof wire passage. Type 4.",
    partNumber: "SI0002004",
    image: "/products/cable-management/seal/SI0002004.jpg",
    specifications: {
      "Type": "Wire Seal",
      "Application": "Waterproof Connectors",
      "Packing": "100 Pcs",
    },
    tags: ["seal", "wire", "waterproof"],
    applications: ["Automotive", "Waterproof Connectors"],
  },
  {
    id: "seal-wire-005",
    name: "Wire Seal - Type 5",
    slug: "wire-seal-type-5",
    category: "Cable Management",
    subcategory: "Wire Seal",
    description: "Wire seal for waterproof wire passage. Type 5.",
    partNumber: "SI0002005",
    image: "/products/cable-management/seal/SI0002005.jpg",
    specifications: {
      "Type": "Wire Seal",
      "Application": "Waterproof Connectors",
      "Packing": "100 Pcs",
    },
    tags: ["seal", "wire", "waterproof"],
    applications: ["Automotive", "Waterproof Connectors"],
  },
  {
    id: "seal-wire-006",
    name: "Wire Seal - Type 6",
    slug: "wire-seal-type-6",
    category: "Cable Management",
    subcategory: "Wire Seal",
    description: "Wire seal for waterproof wire passage. Type 6.",
    partNumber: "SI0002006",
    image: "/products/cable-management/seal/SI0002006.jpg",
    specifications: {
      "Type": "Wire Seal",
      "Application": "Waterproof Connectors",
      "Packing": "100 Pcs",
    },
    tags: ["seal", "wire", "waterproof"],
    applications: ["Automotive", "Waterproof Connectors"],
  },
  {
    id: "seal-wire-007",
    name: "Wire Seal - Type 7",
    slug: "wire-seal-type-7",
    category: "Cable Management",
    subcategory: "Wire Seal",
    description: "Wire seal for waterproof wire passage. Type 7.",
    partNumber: "SI0002007",
    image: "/products/cable-management/seal/SI0002007.jpg",
    specifications: {
      "Type": "Wire Seal",
      "Application": "Waterproof Connectors",
      "Packing": "100 Pcs",
    },
    tags: ["seal", "wire", "waterproof"],
    applications: ["Automotive", "Waterproof Connectors"],
  },
  {
    id: "seal-wire-008",
    name: "Wire Seal - Type 8",
    slug: "wire-seal-type-8",
    category: "Cable Management",
    subcategory: "Wire Seal",
    description: "Wire seal for waterproof wire passage. Type 8.",
    partNumber: "SI0002008",
    image: "/products/cable-management/seal/SI0002008.jpg",
    specifications: {
      "Type": "Wire Seal",
      "Application": "Waterproof Connectors",
      "Packing": "100 Pcs",
    },
    tags: ["seal", "wire", "waterproof"],
    applications: ["Automotive", "Waterproof Connectors"],
  },
  {
    id: "seal-wire-009",
    name: "Wire Seal - Type 9",
    slug: "wire-seal-type-9",
    category: "Cable Management",
    subcategory: "Wire Seal",
    description: "Wire seal for waterproof wire passage. Type 9.",
    partNumber: "SI0002009",
    image: "/products/cable-management/seal/SI0002009.jpg",
    specifications: {
      "Type": "Wire Seal",
      "Application": "Waterproof Connectors",
      "Packing": "100 Pcs",
    },
    tags: ["seal", "wire", "waterproof"],
    applications: ["Automotive", "Waterproof Connectors"],
  },
  {
    id: "seal-dummy-101",
    name: "Dummy Seal - Type 101",
    slug: "dummy-seal-type-101",
    category: "Cable Management",
    subcategory: "Dummy Seal",
    description: "Dummy seal for unused connector cavities.",
    partNumber: "SI0002101",
    image: "/products/cable-management/seal/SI0002101.jpg",
    specifications: {
      "Type": "Dummy Seal",
      "Application": "Unused Cavities",
      "Packing": "100 Pcs",
    },
    tags: ["seal", "dummy", "waterproof"],
    applications: ["Automotive", "Connector Protection"],
  },
  {
    id: "seal-dummy-102",
    name: "Dummy Seal - Type 102",
    slug: "dummy-seal-type-102",
    category: "Cable Management",
    subcategory: "Dummy Seal",
    description: "Dummy seal for unused connector cavities.",
    partNumber: "SI0002102",
    image: "/products/cable-management/seal/SI0002102.jpg",
    specifications: {
      "Type": "Dummy Seal",
      "Application": "Unused Cavities",
      "Packing": "100 Pcs",
    },
    tags: ["seal", "dummy", "waterproof"],
    applications: ["Automotive", "Connector Protection"],
  },
  {
    id: "seal-dummy-plug-111",
    name: "Dummy Plug - Type 111",
    slug: "dummy-plug-type-111",
    category: "Cable Management",
    subcategory: "Dummy Plug",
    description: "Dummy plug for sealing unused connector ports.",
    partNumber: "SI0002111",
    image: "/products/cable-management/seal/SI0002111.jpg",
    specifications: {
      "Type": "Dummy Plug",
      "Application": "Port Sealing",
      "Packing": "100 Pcs",
    },
    tags: ["seal", "dummy", "plug"],
    applications: ["Automotive", "Port Protection"],
  },
  {
    id: "seal-dummy-plug-112",
    name: "Dummy Plug - Type 112",
    slug: "dummy-plug-type-112",
    category: "Cable Management",
    subcategory: "Dummy Plug",
    description: "Dummy plug for sealing unused connector ports.",
    partNumber: "SI0002112",
    image: "/products/cable-management/seal/SI0002112.jpg",
    specifications: {
      "Type": "Dummy Plug",
      "Application": "Port Sealing",
      "Packing": "100 Pcs",
    },
    tags: ["seal", "dummy", "plug"],
    applications: ["Automotive", "Port Protection"],
  },
];

// CORRUGATED PIPES
export const corrugatedPipeProducts: Product[] = [
  {
    id: "cpipe-7mm",
    name: "Corrugated Pipe - 7mm",
    slug: "corrugated-pipe-7mm",
    category: "Cable Management",
    subcategory: "Corrugated Pipe",
    description: "Flexible corrugated pipe for wire protection. 7mm diameter. Sold per meter, rolls available in 25 meters.",
    partNumber: "SI0200007",
    specifications: {
      "Inner Diameter": "6.5mm",
      "Outer Diameter": "10mm",
      "Size": "7mm",
      "Roll Length": "25 Meters",
      "Packing": "Sold per meter",
    },
    tags: ["pipe", "corrugated", "7mm", "wire-protection"],
    applications: ["Automotive", "Wire Bundling", "Cable Protection"],
  },
  {
    id: "cpipe-10mm",
    name: "Corrugated Pipe - 10mm",
    slug: "corrugated-pipe-10mm",
    category: "Cable Management",
    subcategory: "Corrugated Pipe",
    description: "Flexible corrugated pipe for wire protection. 10mm diameter.",
    partNumber: "SI0200010",
    featured: true,
    specifications: {
      "Size": "10mm",
      "Roll Length": "25 Meters",
      "Packing": "Sold per meter",
    },
    tags: ["pipe", "corrugated", "10mm", "wire-protection"],
    applications: ["Automotive", "Wire Bundling"],
  },
  {
    id: "cpipe-12mm",
    name: "Corrugated Pipe - 12mm",
    slug: "corrugated-pipe-12mm",
    category: "Cable Management",
    subcategory: "Corrugated Pipe",
    description: "Flexible corrugated pipe. 12mm diameter.",
    partNumber: "SI0200012",
    specifications: {
      "Size": "12mm",
      "Roll Length": "25 Meters",
      "Packing": "Sold per meter",
    },
    tags: ["pipe", "corrugated", "12mm"],
    applications: ["Automotive", "Wire Bundling"],
  },
  {
    id: "cpipe-14mm",
    name: "Corrugated Pipe - 14mm",
    slug: "corrugated-pipe-14mm",
    category: "Cable Management",
    subcategory: "Corrugated Pipe",
    description: "Flexible corrugated pipe. 14mm diameter.",
    partNumber: "SI0200014",
    specifications: {
      "Size": "14mm",
      "Roll Length": "25 Meters",
      "Packing": "Sold per meter",
    },
    tags: ["pipe", "corrugated", "14mm"],
    applications: ["Automotive", "Wire Bundling"],
  },
  {
    id: "cpipe-16mm",
    name: "Corrugated Pipe - 16mm",
    slug: "corrugated-pipe-16mm",
    category: "Cable Management",
    subcategory: "Corrugated Pipe",
    description: "Flexible corrugated pipe. 16mm diameter.",
    partNumber: "SI0200016",
    featured: true,
    specifications: {
      "Size": "16mm",
      "Roll Length": "25 Meters",
      "Packing": "Sold per meter",
    },
    tags: ["pipe", "corrugated", "16mm"],
    applications: ["Automotive", "Wire Bundling"],
  },
  {
    id: "cpipe-18mm",
    name: "Corrugated Pipe - 18mm",
    slug: "corrugated-pipe-18mm",
    category: "Cable Management",
    subcategory: "Corrugated Pipe",
    description: "Flexible corrugated pipe. 18mm diameter.",
    partNumber: "SI0200018",
    specifications: {
      "Size": "18mm",
      "Roll Length": "25 Meters",
      "Packing": "Sold per meter",
    },
    tags: ["pipe", "corrugated", "18mm"],
    applications: ["Automotive", "Wire Bundling"],
  },
  {
    id: "cpipe-20mm",
    name: "Corrugated Pipe - 20mm",
    slug: "corrugated-pipe-20mm",
    category: "Cable Management",
    subcategory: "Corrugated Pipe",
    description: "Flexible corrugated pipe. 20mm diameter.",
    partNumber: "SI0200020",
    specifications: {
      "Size": "20mm",
      "Roll Length": "25 Meters",
      "Packing": "Sold per meter",
    },
    tags: ["pipe", "corrugated", "20mm"],
    applications: ["Automotive", "Wire Bundling"],
  },
  {
    id: "cpipe-25mm",
    name: "Corrugated Pipe - 25mm",
    slug: "corrugated-pipe-25mm",
    category: "Cable Management",
    subcategory: "Corrugated Pipe",
    description: "Flexible corrugated pipe. 25mm diameter.",
    partNumber: "SI0200025",
    specifications: {
      "Size": "25mm",
      "Roll Length": "25 Meters",
      "Packing": "Sold per meter",
    },
    tags: ["pipe", "corrugated", "25mm"],
    applications: ["Automotive", "Heavy Duty Bundling"],
  },
  {
    id: "cpipe-28mm",
    name: "Corrugated Pipe - 28mm",
    slug: "corrugated-pipe-28mm",
    category: "Cable Management",
    subcategory: "Corrugated Pipe",
    description: "Flexible corrugated pipe. 28mm diameter.",
    partNumber: "SI0200028",
    specifications: {
      "Size": "28mm",
      "Roll Length": "25 Meters",
      "Packing": "Sold per meter",
    },
    tags: ["pipe", "corrugated", "28mm"],
    applications: ["Automotive", "Heavy Duty Bundling"],
  },
  {
    id: "cpipe-32mm",
    name: "Corrugated Pipe - 32mm",
    slug: "corrugated-pipe-32mm",
    category: "Cable Management",
    subcategory: "Corrugated Pipe",
    description: "Flexible corrugated pipe. 32mm diameter.",
    partNumber: "SI0200032",
    specifications: {
      "Size": "32mm",
      "Roll Length": "25 Meters",
      "Packing": "Sold per meter",
    },
    tags: ["pipe", "corrugated", "32mm"],
    applications: ["Commercial Vehicles", "Heavy Duty"],
  },
  {
    id: "cpipe-40mm",
    name: "Corrugated Pipe - 40mm",
    slug: "corrugated-pipe-40mm",
    category: "Cable Management",
    subcategory: "Corrugated Pipe",
    description: "Flexible corrugated pipe. 40mm diameter.",
    partNumber: "SI0200040",
    specifications: {
      "Size": "40mm",
      "Roll Length": "25 Meters",
      "Packing": "Sold per meter",
    },
    tags: ["pipe", "corrugated", "40mm"],
    applications: ["Commercial Vehicles", "Heavy Duty"],
  },
  {
    id: "cpipe-50mm",
    name: "Corrugated Pipe - 50mm",
    slug: "corrugated-pipe-50mm",
    category: "Cable Management",
    subcategory: "Corrugated Pipe",
    description: "Flexible corrugated pipe. 50mm diameter.",
    partNumber: "SI0200050",
    specifications: {
      "Size": "50mm",
      "Roll Length": "25 Meters",
      "Packing": "Sold per meter",
    },
    tags: ["pipe", "corrugated", "50mm"],
    applications: ["Commercial Vehicles", "Extra Heavy Duty"],
  },
  {
    id: "cpipe-63mm",
    name: "Corrugated Pipe - 63mm",
    slug: "corrugated-pipe-63mm",
    category: "Cable Management",
    subcategory: "Corrugated Pipe",
    description: "Flexible corrugated pipe. 63mm diameter.",
    partNumber: "SI0200063",
    specifications: {
      "Size": "63mm",
      "Roll Length": "25 Meters",
      "Packing": "Sold per meter",
    },
    tags: ["pipe", "corrugated", "63mm"],
    applications: ["Commercial Vehicles", "Extra Heavy Duty"],
  },
];

// FLEXIBLE POLYAMIDE CONDUIT (Export Quality)
export const flexibleConduitProducts: Product[] = [
  {
    id: "conduit-pg07",
    name: "Flexible Polyamide Conduit - PG-07 (6.5mm ID / 10mm OD)",
    slug: "flexible-conduit-pg07",
    category: "Cable Management",
    subcategory: "Flexible Conduit",
    description: "Export quality flexible polyamide conduit. PG-07 size. Inner diameter 6.5mm, Outer diameter 10mm. 50 meter roll.",
    partNumber: "SI0200107",
    featured: true,
    specifications: {
      "Size": "PG-07",
      "Inner Diameter": "6.5mm",
      "Outer Diameter": "10mm",
      "Material": "Polyamide",
      "Quality": "Export",
      "Roll Length": "50 Meters",
      "Packing": "100 Pcs glands available",
    },
    tags: ["conduit", "flexible", "polyamide", "pg-07"],
    applications: ["Automotive", "Industrial", "Cable Protection"],
  },
  {
    id: "conduit-pg09",
    name: "Flexible Polyamide Conduit - PG-09 (10mm ID / 13mm OD)",
    slug: "flexible-conduit-pg09",
    category: "Cable Management",
    subcategory: "Flexible Conduit",
    description: "Export quality flexible polyamide conduit. PG-09 size.",
    partNumber: "SI0200109",
    specifications: {
      "Size": "PG-09",
      "Inner Diameter": "10mm",
      "Outer Diameter": "13mm",
      "Material": "Polyamide",
      "Quality": "Export",
      "Roll Length": "50 Meters",
    },
    tags: ["conduit", "flexible", "polyamide", "pg-09"],
    applications: ["Automotive", "Industrial"],
  },
  {
    id: "conduit-pg11",
    name: "Flexible Polyamide Conduit - PG-11 (12mm ID / 15.8mm OD)",
    slug: "flexible-conduit-pg11",
    category: "Cable Management",
    subcategory: "Flexible Conduit",
    description: "Export quality flexible polyamide conduit. PG-11 size.",
    partNumber: "SI0200111",
    specifications: {
      "Size": "PG-11",
      "Inner Diameter": "12mm",
      "Outer Diameter": "15.8mm",
      "Material": "Polyamide",
      "Quality": "Export",
      "Roll Length": "50 Meters",
    },
    tags: ["conduit", "flexible", "polyamide", "pg-11"],
    applications: ["Automotive", "Industrial"],
  },
  {
    id: "conduit-pg13",
    name: "Flexible Polyamide Conduit - PG-13 (14mm ID / 18.5mm OD)",
    slug: "flexible-conduit-pg13",
    category: "Cable Management",
    subcategory: "Flexible Conduit",
    description: "Export quality flexible polyamide conduit. PG-13 size.",
    partNumber: "SI0200113",
    specifications: {
      "Size": "PG-13",
      "Inner Diameter": "14mm",
      "Outer Diameter": "18.5mm",
      "Material": "Polyamide",
      "Quality": "Export",
      "Roll Length": "50 Meters",
    },
    tags: ["conduit", "flexible", "polyamide", "pg-13"],
    applications: ["Automotive", "Industrial"],
  },
  {
    id: "conduit-pg16",
    name: "Flexible Polyamide Conduit - PG-16 (17mm ID / 21.2mm OD)",
    slug: "flexible-conduit-pg16",
    category: "Cable Management",
    subcategory: "Flexible Conduit",
    description: "Export quality flexible polyamide conduit. PG-16 size.",
    partNumber: "SI0200116",
    featured: true,
    specifications: {
      "Size": "PG-16",
      "Inner Diameter": "17mm",
      "Outer Diameter": "21.2mm",
      "Material": "Polyamide",
      "Quality": "Export",
      "Roll Length": "50 Meters",
    },
    tags: ["conduit", "flexible", "polyamide", "pg-16"],
    applications: ["Automotive", "Industrial"],
  },
  {
    id: "conduit-pg21",
    name: "Flexible Polyamide Conduit - PG-21 (23mm ID / 28.5mm OD)",
    slug: "flexible-conduit-pg21",
    category: "Cable Management",
    subcategory: "Flexible Conduit",
    description: "Export quality flexible polyamide conduit. PG-21 size.",
    partNumber: "SI0200121",
    specifications: {
      "Size": "PG-21",
      "Inner Diameter": "23mm",
      "Outer Diameter": "28.5mm",
      "Material": "Polyamide",
      "Quality": "Export",
      "Roll Length": "50 Meters",
    },
    tags: ["conduit", "flexible", "polyamide", "pg-21"],
    applications: ["Automotive", "Industrial"],
  },
  {
    id: "conduit-pg29",
    name: "Flexible Polyamide Conduit - PG-29 (29mm ID / 34.5mm OD)",
    slug: "flexible-conduit-pg29",
    category: "Cable Management",
    subcategory: "Flexible Conduit",
    description: "Export quality flexible polyamide conduit. PG-29 size.",
    partNumber: "SI0200129",
    specifications: {
      "Size": "PG-29",
      "Inner Diameter": "29mm",
      "Outer Diameter": "34.5mm",
      "Material": "Polyamide",
      "Quality": "Export",
      "Roll Length": "25 Meters",
    },
    tags: ["conduit", "flexible", "polyamide", "pg-29"],
    applications: ["Industrial", "Heavy Duty"],
  },
  {
    id: "conduit-pg36",
    name: "Flexible Polyamide Conduit - PG-36 (36mm ID / 42.5mm OD)",
    slug: "flexible-conduit-pg36",
    category: "Cable Management",
    subcategory: "Flexible Conduit",
    description: "Export quality flexible polyamide conduit. PG-36 size.",
    partNumber: "SI0200136",
    specifications: {
      "Size": "PG-36",
      "Inner Diameter": "36mm",
      "Outer Diameter": "42.5mm",
      "Material": "Polyamide",
      "Quality": "Export",
      "Roll Length": "25 Meters",
    },
    tags: ["conduit", "flexible", "polyamide", "pg-36"],
    applications: ["Industrial", "Heavy Duty"],
  },
  {
    id: "conduit-pg48",
    name: "Flexible Polyamide Conduit - PG-48 (48mm ID / 54.5mm OD)",
    slug: "flexible-conduit-pg48",
    category: "Cable Management",
    subcategory: "Flexible Conduit",
    description: "Export quality flexible polyamide conduit. PG-48 size.",
    partNumber: "SI0200148",
    specifications: {
      "Size": "PG-48",
      "Inner Diameter": "48mm",
      "Outer Diameter": "54.5mm",
      "Material": "Polyamide",
      "Quality": "Export",
      "Roll Length": "25 Meters",
    },
    tags: ["conduit", "flexible", "polyamide", "pg-48"],
    applications: ["Industrial", "Extra Heavy Duty"],
  },
];

// PG GLANDS WITH LOCK NUT
export const pgGlandProducts: Product[] = [
  {
    id: "pg-gland-07",
    name: "PG Gland with Lock Nut - PG-07",
    slug: "pg-gland-pg07",
    category: "Cable Management",
    subcategory: "PG Gland",
    description: "PG-07 cable gland with lock nut for secure cable entry. Compatible with PG-07 conduits.",
    partNumber: "SG0200107",
    featured: true,
    specifications: {
      "Size": "PG-07",
      "Compatible Hose": "PG-07 Conduit",
      "Includes": "Lock Nut",
      "Packing": "100 Pcs",
    },
    tags: ["gland", "pg-07", "cable-entry", "lock-nut"],
    applications: ["Automotive", "Panel Mounting", "Cable Entry"],
  },
  {
    id: "pg-gland-09",
    name: "PG Gland with Lock Nut - PG-09",
    slug: "pg-gland-pg09",
    category: "Cable Management",
    subcategory: "PG Gland",
    description: "PG-09 cable gland with lock nut.",
    partNumber: "SG0200109",
    specifications: {
      "Size": "PG-09",
      "Compatible Hose": "PG-09 Conduit",
      "Includes": "Lock Nut",
      "Packing": "100 Pcs",
    },
    tags: ["gland", "pg-09", "cable-entry"],
    applications: ["Automotive", "Panel Mounting"],
  },
  {
    id: "pg-gland-11",
    name: "PG Gland with Lock Nut - PG-11",
    slug: "pg-gland-pg11",
    category: "Cable Management",
    subcategory: "PG Gland",
    description: "PG-11 cable gland with lock nut.",
    partNumber: "SG0200111",
    specifications: {
      "Size": "PG-11",
      "Compatible Hose": "PG-11 Conduit",
      "Includes": "Lock Nut",
      "Packing": "100 Pcs",
    },
    tags: ["gland", "pg-11", "cable-entry"],
    applications: ["Automotive", "Panel Mounting"],
  },
  {
    id: "pg-gland-13",
    name: "PG Gland with Lock Nut - PG-13",
    slug: "pg-gland-pg13",
    category: "Cable Management",
    subcategory: "PG Gland",
    description: "PG-13 cable gland with lock nut.",
    partNumber: "SG0200113",
    specifications: {
      "Size": "PG-13",
      "Compatible Hose": "PG-13 Conduit",
      "Includes": "Lock Nut",
      "Packing": "100 Pcs",
    },
    tags: ["gland", "pg-13", "cable-entry"],
    applications: ["Automotive", "Panel Mounting"],
  },
  {
    id: "pg-gland-16",
    name: "PG Gland with Lock Nut - PG-16",
    slug: "pg-gland-pg16",
    category: "Cable Management",
    subcategory: "PG Gland",
    description: "PG-16 cable gland with lock nut.",
    partNumber: "SG0200116",
    featured: true,
    specifications: {
      "Size": "PG-16",
      "Compatible Hose": "PG-16 Conduit",
      "Includes": "Lock Nut",
      "Packing": "100 Pcs",
    },
    tags: ["gland", "pg-16", "cable-entry"],
    applications: ["Automotive", "Panel Mounting"],
  },
  {
    id: "pg-gland-21",
    name: "PG Gland with Lock Nut - PG-21",
    slug: "pg-gland-pg21",
    category: "Cable Management",
    subcategory: "PG Gland",
    description: "PG-21 cable gland with lock nut.",
    partNumber: "SG0200121",
    specifications: {
      "Size": "PG-21",
      "Compatible Hose": "PG-21 Conduit",
      "Includes": "Lock Nut",
      "Packing": "100 Pcs",
    },
    tags: ["gland", "pg-21", "cable-entry"],
    applications: ["Automotive", "Panel Mounting"],
  },
  {
    id: "pg-gland-29",
    name: "PG Gland with Lock Nut - PG-29",
    slug: "pg-gland-pg29",
    category: "Cable Management",
    subcategory: "PG Gland",
    description: "PG-29 cable gland with lock nut.",
    partNumber: "SG0200129",
    specifications: {
      "Size": "PG-29",
      "Compatible Hose": "PG-29 Conduit",
      "Includes": "Lock Nut",
      "Packing": "50 Pcs",
    },
    tags: ["gland", "pg-29", "cable-entry"],
    applications: ["Industrial", "Panel Mounting"],
  },
  {
    id: "pg-gland-36",
    name: "PG Gland with Lock Nut - PG-36",
    slug: "pg-gland-pg36",
    category: "Cable Management",
    subcategory: "PG Gland",
    description: "PG-36 cable gland with lock nut.",
    partNumber: "SG0200136",
    specifications: {
      "Size": "PG-36",
      "Compatible Hose": "PG-36 Conduit",
      "Includes": "Lock Nut",
      "Packing": "10 Pcs",
    },
    tags: ["gland", "pg-36", "cable-entry"],
    applications: ["Industrial", "Heavy Duty"],
  },
  {
    id: "pg-gland-48",
    name: "PG Gland with Lock Nut - PG-48",
    slug: "pg-gland-pg48",
    category: "Cable Management",
    subcategory: "PG Gland",
    description: "PG-48 cable gland with lock nut.",
    partNumber: "SG0200148",
    specifications: {
      "Size": "PG-48",
      "Compatible Hose": "PG-48 Conduit",
      "Includes": "Lock Nut",
      "Packing": "10 Pcs",
    },
    tags: ["gland", "pg-48", "cable-entry"],
    applications: ["Industrial", "Extra Heavy Duty"],
  },
];

// METRIC GLANDS WITH LOCK NUT
export const metricGlandProducts: Product[] = [
  {
    id: "metric-gland-07",
    name: "Metric Gland with Lock Nut - M-07",
    slug: "metric-gland-m07",
    category: "Cable Management",
    subcategory: "Metric Gland",
    description: "Metric M-07 cable gland with lock nut. Compatible with metric conduit systems.",
    partNumber: "SGC0200107",
    specifications: {
      "Size": "M-07",
      "Thread": "Metric",
      "Includes": "Lock Nut",
      "Packing": "100 Pcs",
    },
    tags: ["gland", "metric", "m-07", "cable-entry"],
    applications: ["Automotive", "Metric Systems"],
  },
  {
    id: "metric-gland-09",
    name: "Metric Gland with Lock Nut - M-09",
    slug: "metric-gland-m09",
    category: "Cable Management",
    subcategory: "Metric Gland",
    description: "Metric M-09 cable gland with lock nut.",
    partNumber: "SGC0200109",
    specifications: {
      "Size": "M-09",
      "Thread": "Metric",
      "Includes": "Lock Nut",
      "Packing": "100 Pcs",
    },
    tags: ["gland", "metric", "m-09"],
    applications: ["Automotive", "Metric Systems"],
  },
  {
    id: "metric-gland-11",
    name: "Metric Gland with Lock Nut - M-11",
    slug: "metric-gland-m11",
    category: "Cable Management",
    subcategory: "Metric Gland",
    description: "Metric M-11 cable gland with lock nut.",
    partNumber: "SGC0200111",
    specifications: {
      "Size": "M-11",
      "Thread": "Metric",
      "Includes": "Lock Nut",
      "Packing": "100 Pcs",
    },
    tags: ["gland", "metric", "m-11"],
    applications: ["Automotive", "Metric Systems"],
  },
  {
    id: "metric-gland-13",
    name: "Metric Gland with Lock Nut - M-13",
    slug: "metric-gland-m13",
    category: "Cable Management",
    subcategory: "Metric Gland",
    description: "Metric M-13 cable gland with lock nut.",
    partNumber: "SGC0200113",
    specifications: {
      "Size": "M-13",
      "Thread": "Metric",
      "Includes": "Lock Nut",
      "Packing": "100 Pcs",
    },
    tags: ["gland", "metric", "m-13"],
    applications: ["Automotive", "Metric Systems"],
  },
  {
    id: "metric-gland-16",
    name: "Metric Gland with Lock Nut - M-16",
    slug: "metric-gland-m16",
    category: "Cable Management",
    subcategory: "Metric Gland",
    description: "Metric M-16 cable gland with lock nut.",
    partNumber: "SGC0200116",
    featured: true,
    specifications: {
      "Size": "M-16",
      "Thread": "Metric",
      "Includes": "Lock Nut",
      "Packing": "100 Pcs",
    },
    tags: ["gland", "metric", "m-16"],
    applications: ["Automotive", "Metric Systems"],
  },
  {
    id: "metric-gland-21",
    name: "Metric Gland with Lock Nut - M-21",
    slug: "metric-gland-m21",
    category: "Cable Management",
    subcategory: "Metric Gland",
    description: "Metric M-21 cable gland with lock nut.",
    partNumber: "SGC0200121",
    specifications: {
      "Size": "M-21",
      "Thread": "Metric",
      "Includes": "Lock Nut",
      "Packing": "100 Pcs",
    },
    tags: ["gland", "metric", "m-21"],
    applications: ["Automotive", "Metric Systems"],
  },
  {
    id: "metric-gland-29",
    name: "Metric Gland with Lock Nut - M-29",
    slug: "metric-gland-m29",
    category: "Cable Management",
    subcategory: "Metric Gland",
    description: "Metric M-29 cable gland with lock nut.",
    partNumber: "SGC0200129",
    specifications: {
      "Size": "M-29",
      "Thread": "Metric",
      "Includes": "Lock Nut",
      "Packing": "50 Pcs",
    },
    tags: ["gland", "metric", "m-29"],
    applications: ["Industrial", "Metric Systems"],
  },
  {
    id: "metric-gland-36",
    name: "Metric Gland with Lock Nut - M-36",
    slug: "metric-gland-m36",
    category: "Cable Management",
    subcategory: "Metric Gland",
    description: "Metric M-36 cable gland with lock nut.",
    partNumber: "SG0C200136",
    specifications: {
      "Size": "M-36",
      "Thread": "Metric",
      "Includes": "Lock Nut",
      "Packing": "10 Pcs",
    },
    tags: ["gland", "metric", "m-36"],
    applications: ["Industrial", "Heavy Duty"],
  },
  {
    id: "metric-gland-48",
    name: "Metric Gland with Lock Nut - M-48",
    slug: "metric-gland-m48",
    category: "Cable Management",
    subcategory: "Metric Gland",
    description: "Metric M-48 cable gland with lock nut.",
    partNumber: "SG0C200148",
    specifications: {
      "Size": "M-48",
      "Thread": "Metric",
      "Includes": "Lock Nut",
      "Packing": "10 Pcs",
    },
    tags: ["gland", "metric", "m-48"],
    applications: ["Industrial", "Extra Heavy Duty"],
  },
];
