import { Product } from '../types';

// ============================================
// SWITCHES
// ============================================
export const switchProducts: Product[] = [
  {
    id: "switch-1",
    name: "Push Pull Switch",
    slug: "push-pull-switch",
    category: "Switches",
    description: "Universal push-pull switches for automotive lighting and accessory control. Available in various types: Long Deluxe, Long Regular, Small Deluxe, Long Big Nob, Extra Long.",
    featured: true,
    specifications: {
      "Type": "Push Pull",
      "Applications": "Lighting, Accessories",
      "Variants": "Multiple types available",
    },
    tags: ["switch", "push-pull", "automotive"],
    applications: ["Automotive", "Lighting Control"],
  },
  {
    id: "switch-2",
    name: "Headlight Switch",
    slug: "headlight-switch",
    category: "Switches",
    description: "Headlight control switches for vehicles.",
    specifications: {
      "Type": "Rotary/Push-Pull",
      "Applications": "Headlight control",
    },
    tags: ["switch", "headlight"],
    applications: ["Automotive", "Lighting"],
  },
  {
    id: "switch-3",
    name: "Toggle Switch",
    slug: "toggle-switch",
    category: "Switches",
    description: "Toggle switches for automotive applications.",
    specifications: {
      "Type": "Toggle",
      "Applications": "General automotive switching",
    },
    tags: ["switch", "toggle"],
    applications: ["Automotive"],
  },
  {
    id: "switch-4",
    name: "Horn Button",
    slug: "horn-button",
    category: "Switches",
    description: "Horn button switches for vehicle horn activation.",
    specifications: {
      "Type": "Push Button",
      "Applications": "Horn activation",
    },
    tags: ["switch", "horn", "button"],
    applications: ["Automotive"],
  },
  {
    id: "switch-5",
    name: "Starter/Horn Button Brass Body",
    slug: "starter-horn-button-brass",
    category: "Switches",
    description: "Heavy-duty starter and horn button with brass body construction.",
    specifications: {
      "Type": "Push Button",
      "Material": "Brass Body",
      "Applications": "Starter, Horn",
    },
    tags: ["switch", "starter", "horn", "brass"],
    applications: ["Automotive", "Heavy Duty"],
  },
];

// ============================================
// FLASHERS
// ============================================
export const flasherProducts: Product[] = [
  {
    id: "flasher-1",
    name: "Electronic Flasher 12V",
    slug: "electronic-flasher-12v",
    category: "Flasher",
    description: "Electronic turn signal flasher relay 12V. Compatible with LED and incandescent bulbs.",
    partNumber: "SEF31211",
    featured: true,
    specifications: {
      "Type": "Electronic",
      "Voltage": "12V",
      "Compatibility": "LED, Incandescent",
      "Applications": "Turn signals, Hazard lights",
    },
    tags: ["flasher", "electronic", "12v"],
    applications: ["Automotive", "2-Wheeler", "4-Wheeler"],
  },
  {
    id: "flasher-2",
    name: "Electronic Flasher 24V",
    slug: "electronic-flasher-24v",
    category: "Flasher",
    description: "Electronic turn signal flasher relay 24V for commercial vehicles.",
    partNumber: "SEF32411",
    specifications: {
      "Type": "Electronic",
      "Voltage": "24V",
      "Compatibility": "LED, Incandescent",
      "Applications": "Turn signals, Hazard lights",
    },
    tags: ["flasher", "electronic", "24v"],
    applications: ["Commercial Vehicles"],
  },
  {
    id: "flasher-3",
    name: "Musical Flasher 12V",
    slug: "musical-flasher-12v",
    category: "Flasher",
    description: "Musical flasher with melody feature for turn signal indication 12V.",
    partNumber: "SMF31202",
    specifications: {
      "Type": "Musical/Melody",
      "Voltage": "12V",
      "Feature": "Audio indication",
      "Applications": "Turn signals",
    },
    tags: ["flasher", "musical", "12v"],
    applications: ["Automotive"],
  },
  {
    id: "flasher-4",
    name: "Musical Flasher 24V",
    slug: "musical-flasher-24v",
    category: "Flasher",
    description: "Musical flasher with melody feature for turn signal indication 24V.",
    partNumber: "SMF32402",
    specifications: {
      "Type": "Musical/Melody",
      "Voltage": "24V",
      "Feature": "Audio indication",
      "Applications": "Turn signals",
    },
    tags: ["flasher", "musical", "24v"],
    applications: ["Commercial Vehicles"],
  },
];

// ============================================
// RELAYS
// ============================================
export const relayProducts: Product[] = [
  {
    id: "relay-1",
    name: "2 Wheeler Relay",
    slug: "2-wheeler-relay",
    category: "Relay",
    subcategory: "2 Wheeler",
    description: "Relay designed for two-wheeler motorcycles and scooters. 4 Pin 12V.",
    specifications: {
      "Compatible": "2 Wheelers",
      "Voltage": "12V",
      "Pins": "4",
    },
    tags: ["relay", "2-wheeler"],
    applications: ["Motorcycles", "Scooters"],
  },
  {
    id: "relay-2",
    name: "Starting Relay 12V",
    slug: "starting-relay-12v",
    category: "Relay",
    subcategory: "Starting Relay",
    description: "Starter motor relay for vehicle ignition systems. Suitable for 2 & 4 Wheeler.",
    partNumber: "S2WR21201",
    specifications: {
      "Type": "Starter Relay",
      "Voltage": "12V",
      "Applications": "Ignition system",
    },
    tags: ["relay", "starting", "12v"],
    applications: ["Automotive", "Starting System"],
  },
  {
    id: "relay-3",
    name: "4 Wheeler Relay 12V",
    slug: "4-wheeler-relay-12v",
    category: "Relay",
    subcategory: "4 Wheeler",
    description: "Relay designed for four-wheeler cars and SUVs. 4 Pin 12V.",
    featured: true,
    specifications: {
      "Compatible": "4 Wheelers",
      "Voltage": "12V",
      "Pins": "4",
    },
    tags: ["relay", "4-wheeler", "12v"],
    applications: ["Cars", "SUVs"],
  },
  {
    id: "relay-4",
    name: "4 Wheeler Relay 24V",
    slug: "4-wheeler-relay-24v",
    category: "Relay",
    subcategory: "4 Wheeler",
    description: "Relay designed for commercial vehicles. 4 Pin 24V.",
    specifications: {
      "Compatible": "Commercial Vehicles",
      "Voltage": "24V",
      "Pins": "4",
    },
    tags: ["relay", "4-wheeler", "24v"],
    applications: ["Commercial Vehicles"],
  },
  {
    id: "relay-5",
    name: "Head Light Relay 12V",
    slug: "headlight-relay-12v",
    category: "Relay",
    subcategory: "Headlight Relay",
    description: "High-power relay for headlight circuits. Improves light output and protects switch. 6 Pin with wire.",
    partNumber: "SR61201",
    featured: true,
    specifications: {
      "Type": "Headlight Relay",
      "Voltage": "12V",
      "Rating": "30A/40A",
      "Pins": "6",
      "Applications": "Headlight upgrade",
    },
    tags: ["relay", "headlight", "12v"],
    applications: ["Automotive", "Lighting"],
  },
  {
    id: "relay-6",
    name: "Head Light Relay 24V",
    slug: "headlight-relay-24v",
    category: "Relay",
    subcategory: "Headlight Relay",
    description: "High-power relay for headlight circuits in commercial vehicles. 6 Pin with wire.",
    partNumber: "SR62401",
    specifications: {
      "Type": "Headlight Relay",
      "Voltage": "24V",
      "Rating": "30A/40A",
      "Pins": "6",
      "Applications": "Headlight upgrade",
    },
    tags: ["relay", "headlight", "24v"],
    applications: ["Commercial Vehicles", "Lighting"],
  },
  {
    id: "relay-7",
    name: "Horn Relay 3 Pin 12V",
    slug: "horn-relay-3pin-12v",
    category: "Relay",
    subcategory: "Horn Relay",
    description: "Horn relay with 3 pin configuration for 12V systems.",
    partNumber: "SR31201",
    specifications: {
      "Type": "Horn Relay",
      "Voltage": "12V",
      "Pins": "3",
      "Applications": "Horn circuits",
    },
    tags: ["relay", "horn", "12v"],
    applications: ["Automotive"],
  },
  {
    id: "relay-8",
    name: "5 Pin Micro Relay 12V",
    slug: "5-pin-micro-relay-12v",
    category: "Relay",
    subcategory: "Micro Relay",
    description: "Compact 5 pin micro relay for 12V automotive applications.",
    partNumber: "SR51201",
    specifications: {
      "Type": "Micro Relay",
      "Voltage": "12V",
      "Pins": "5",
    },
    tags: ["relay", "micro", "12v"],
    applications: ["Automotive"],
  },
  {
    id: "relay-9",
    name: "5 Pin Micro Relay 24V",
    slug: "5-pin-micro-relay-24v",
    category: "Relay",
    subcategory: "Micro Relay",
    description: "Compact 5 pin micro relay for 24V commercial vehicle applications.",
    partNumber: "SR52401",
    specifications: {
      "Type": "Micro Relay",
      "Voltage": "24V",
      "Pins": "5",
    },
    tags: ["relay", "micro", "24v"],
    applications: ["Commercial Vehicles"],
  },
  {
    id: "relay-10",
    name: "Mini Relay 4 Pin 12V",
    slug: "mini-relay-4pin-12v",
    category: "Relay",
    subcategory: "Mini Relay",
    description: "Compact mini relay with 4 pin configuration for 12V systems.",
    specifications: {
      "Type": "Mini Relay",
      "Voltage": "12V",
      "Pins": "4",
    },
    tags: ["relay", "mini", "12v"],
    applications: ["Automotive"],
  },
  {
    id: "relay-11",
    name: "Transparent Relay 4 Pin 12V",
    slug: "transparent-relay-4pin-12v",
    category: "Relay",
    subcategory: "Transparent Relay",
    description: "Transparent housing relay for easy fault diagnosis. 4 Pin 12V.",
    specifications: {
      "Type": "Transparent",
      "Voltage": "12V",
      "Pins": "4",
    },
    tags: ["relay", "transparent", "12v"],
    applications: ["Automotive"],
  },
];

// ============================================
// TUNERS
// ============================================
export const tunerProducts: Product[] = [
  {
    id: "tuner-1",
    name: "4 Way Tuner",
    slug: "4-way-tuner",
    category: "Tuner",
    description: "4-way electrical distribution tuner for vehicle wiring.",
    specifications: {
      "Ways": "4",
      "Applications": "Electrical distribution",
    },
    tags: ["tuner", "4-way", "distribution"],
    applications: ["Automotive", "Electrical Distribution"],
  },
  {
    id: "tuner-2",
    name: "7 Way Tuner",
    slug: "7-way-tuner",
    category: "Tuner",
    description: "7-way electrical distribution tuner.",
    specifications: {
      "Ways": "7",
      "Applications": "Electrical distribution",
    },
    tags: ["tuner", "7-way"],
    applications: ["Automotive", "Electrical Distribution"],
  },
  {
    id: "tuner-3",
    name: "8 Way Tuner",
    slug: "8-way-tuner",
    category: "Tuner",
    description: "8-way electrical distribution tuner.",
    specifications: {
      "Ways": "8",
      "Applications": "Electrical distribution",
    },
    tags: ["tuner", "8-way"],
    applications: ["Automotive", "Electrical Distribution"],
  },
];
